$axure.loadCurrentPage({
  "url":"首页.html",
  "generationDate":new Date(1463658740545.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5c3f128d760f41518515a38db7ccede8",
    "type":"Axure:Page",
    "name":"首页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a53c1a44c028446a89d109b2813655b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":798,
              "height":41},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ec225b47b8b4b0399bed8483ce2200d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":798,
                  "height":41},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"28dfe58f539e4772a9798add4deb6571",
          "label":"内容",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":51},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"aabc28ac281040a4a77d632aeac6abe8",
              "label":"收信",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7911f8e305844af8b7b27d61f9878f02",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":137,
                      "y":0},
                    "size":{
                      "width":661,
                      "height":489},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df4f233d8dbe4a5cb175b9b4dcb4d071",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":137,
                          "y":0},
                        "size":{
                          "width":661,
                          "height":489},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u3.png"}},
{
                  "id":"4c34cf160c5b4bd5a3e1e274176e6299",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"18px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":644,
                      "y":410.75},
                    "size":{
                      "width":96,
                      "height":42},
                    "cornerRadiusTopLeft":"30"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"30bc9dfed0d949c4a27c485736656d74",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"18px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":644,
                          "y":410.75},
                        "size":{
                          "width":96,
                          "height":42},
                        "cornerRadiusTopLeft":"30"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 写信给***",
                              "target":{
                                "targetType":"page",
                                "url":"写信给___.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u5.png"}},
{
                  "id":"1b2db4d93b7b45ed8247629838ba6b18",
                  "label":"收件箱导航",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":52},
                    "size":{
                      "width":10,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"81ec87014d11400f8c7ec923780d7c35",
                      "label":"已读",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"324a0911aec94fb5adf3c40da80b81ce",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":119,
                              "height":437},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ee2ff7a7e42b4ea397b2cd1f41a24e26",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":119,
                                  "height":437},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u8.png"}},
{
                          "id":"b6d4d119a8b44aaf89ccfb9d11e1f7e2",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":60},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1bbeeb689d3c458e842f43d7d564fa5c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":60},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"677935c987c34a53b1c7136fbb3c850e",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":118},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1e783469f3bc47828eb4e5ab61542d48",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":118},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"32ae59a76dc14b338a88d4a849a43061",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":176},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1e693885f12b45b78cb8aa4b50f6ea5b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":176},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"405b8a0c3d234113a3e79492db6e6227",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":234},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"89f5de0fbef3434598fe5777816054c5",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":234},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"d838093848c64d639b2fbff72f0392a2",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":292},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"36650022d6e14551b905b1b2193b980a",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":292},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"e7dbe5d2c9ec4ca1afbab5dbc9d7fd64",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":350},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"23940dfd01a0442ab868df12b06bc4ae",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":350},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"fb104fe50fc7450c8a9e848a206c2d77",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1},
                            "location":{
                              "x":26,
                              "y":19},
                            "size":{
                              "width":67,
                              "height":16}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"7a4546283ff640d5a6714144a0dac5d3",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "foreGroundFill":{
                                  "fillType":"solid",
                                  "color":0xFF999999,
                                  "opacity":1},
                                "location":{
                                  "x":26,
                                  "y":19},
                                "size":{
                                  "width":67,
                                  "height":16}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"resources/images/transparent.gif"}}]},
{
                      "id":"f6c3a44acbe34183b2d80a76022af2b1",
                      "label":"未读",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"b3dfb053ef004096a3e5ded50c98fd4c",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "size":{
                              "width":119,
                              "height":437},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"508f218b3d154aa6b14c0f0e352a4f54",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "size":{
                                  "width":119,
                                  "height":437},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u8.png"}},
{
                          "id":"ea3f9a6335e54e569162dee0ce1acd62",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":13},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"33646037a1ed487f8294de284c0192a6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":13},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}},
{
                          "id":"d0d1be02ac5544bfa74aaf6f1737c14a",
                          "label":"",
                          "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":8,
                              "y":71},
                            "size":{
                              "width":103,
                              "height":48},
                            "cornerRadiusTopLeft":"8"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"4ae580a652624e88b26f60d2093b0d18",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"1b2db4d93b7b45ed8247629838ba6b18",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "location":{
                                  "x":8,
                                  "y":71},
                                "size":{
                                  "width":103,
                                  "height":48},
                                "cornerRadiusTopLeft":"8"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/首页/u10.png"}}]}]},
{
                  "id":"17108429f5ca4f5e88737d47a23dae7c",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":65,
                      "y":0},
                    "size":{
                      "width":52,
                      "height":42},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e8236a522ae34b33837b4f4e5b8ad146",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":65,
                          "y":0},
                        "size":{
                          "width":52,
                          "height":42},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 收件箱导航 to 已读 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["1b2db4d93b7b45ed8247629838ba6b18"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"a4ed043d45bf4fc29f53735ce9ccb9ca",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":3,
                      "y":0},
                    "size":{
                      "width":52,
                      "height":42},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"14fdec0cff2b4a76a108626f9639acd1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":3,
                          "y":0},
                        "size":{
                          "width":52,
                          "height":42},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 收件箱导航 to 未读 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["1b2db4d93b7b45ed8247629838ba6b18"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u30.png"}},
{
                  "id":"ea24446e978a47249f0af1d074777127",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFF0000},
                    "location":{
                      "x":40.5,
                      "y":0},
                    "size":{
                      "width":20,
                      "height":20},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "cornerRadiusTopLeft":"25"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9b1e18fa6b434744a86914fa15193d5f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFF0000},
                        "location":{
                          "x":40.5,
                          "y":0},
                        "size":{
                          "width":20,
                          "height":20},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "cornerRadiusTopLeft":"25"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u34.png"}}]},
{
              "id":"67e7aa526f294a679b7bc3447653fb25",
              "label":"空",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"8d88bbf4f4434313b4f4e2a5a6027878",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":798,
                      "height":489},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e40714a20e0f4d7a9a4dae9682d41056",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":798,
                          "height":489},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u36.png"}},
{
                  "id":"5677098bc52b4556b8cc7f25e2d878c0",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                    "fontSize":"18px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":323,
                      "y":171},
                    "size":{
                      "width":152,
                      "height":54},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"343229686f964a6aae72811ede0941ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                        "fontSize":"18px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":323,
                          "y":171},
                        "size":{
                          "width":152,
                          "height":54},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 写信给Ta",
                              "target":{
                                "targetType":"page",
                                "url":"写信给ta.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u38.png"}},
{
                  "id":"d9203771d21a471a84da368af38270c8",
                  "label":"",
                  "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正兰亭超细黑简体 Regular', '方正兰亭超细黑简体'",
                    "fontSize":"20px",
                    "fontWeight":"400",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":245,
                      "y":101},
                    "size":{
                      "width":308,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69540251a5394effae46b02cabddf5c2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"28dfe58f539e4772a9798add4deb6571",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正兰亭超细黑简体 Regular', '方正兰亭超细黑简体'",
                        "fontSize":"20px",
                        "fontWeight":"400",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":245,
                          "y":101},
                        "size":{
                          "width":308,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"5d77921a14a04168a276f7547589b9a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Bold', '方正舒体'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":29,
              "y":6},
            "size":{
              "width":59,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"691b4f43d0c14d77a25331268eb6744e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Bold', '方正舒体'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":29,
                  "y":6},
                "size":{
                  "width":59,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ef2c778805e460abb178503143c938e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":5},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"120"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65bd99223c4442adb68f158bb3cc9dc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":5},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"120"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u44.png"}},
{
          "id":"05c0363e8d744f3285d9ebce2ffb309e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":755.5,
              "y":11},
            "size":{
              "width":19,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bc818505bbd42dab57308f6d15e6520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":755.5,
                  "y":11},
                "size":{
                  "width":19,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u46.png"}},
{
          "id":"04512c70897f48269b2188dce72e1919",
          "label":"断绝联系",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":299,
              "y":35},
            "size":{
              "width":200,
              "height":54},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"ea82f0c81f16435e84aefdece8d71827",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f3734067f28e4a7ab0b32638631d876a",
                  "label":"",
                  "parentDynamicPanel":"04512c70897f48269b2188dce72e1919",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF1E1E1E,
                      "opacity":1},
                    "location":{
                      "x":7,
                      "y":4},
                    "size":{
                      "width":185,
                      "height":36},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000},
                    "cornerRadiusTopLeft":"8"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a5fc61e300f429b85629fe87f6a6370",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"04512c70897f48269b2188dce72e1919",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF1E1E1E,
                          "opacity":1},
                        "location":{
                          "x":7,
                          "y":4},
                        "size":{
                          "width":185,
                          "height":36},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000},
                        "cornerRadiusTopLeft":"8"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 内容 to 空 淡入淡出 out 500ms 淡入淡出 in 500ms 显示隐藏",
                              "panelsToStates":[{
                                  "panelPath":["28dfe58f539e4772a9798add4deb6571"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":true,
                                    "options":{
                                      "animateOut":{
                                        "easing":"fade",
                                        "duration":500},
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 This 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["f3734067f28e4a7ab0b32638631d876a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 标题栏",
                              "objectsToFades":[{
                                  "objectPath":["1ab90ed1c46d42f1bb6f9ab88c5a2133"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u49.png"}}]}]},
{
          "id":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
          "label":"标题栏",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":345,
              "y":5},
            "size":{
              "width":401,
              "height":30}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"23d4816eec224cc389ba196a573db883",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"192d33b0de3443d4810173846d2c4183",
                  "label":"",
                  "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":365,
                      "y":0},
                    "size":{
                      "width":30,
                      "height":30},
                    "cornerRadiusTopLeft":"120"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"333a83aadb054053afad7b3355b78b2a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":365,
                          "y":0},
                        "size":{
                          "width":30,
                          "height":30},
                        "cornerRadiusTopLeft":"120"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u44.png"}},
{
                  "id":"e8090581f8ce46679ffada4f3cc719ed",
                  "label":"",
                  "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Arial Negreta', 'Arial'",
                    "fontSize":"14px",
                    "fontWeight":"700",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":253,
                      "y":0},
                    "size":{
                      "width":97,
                      "height":30},
                    "cornerRadiusTopLeft":"120"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce0e430f1b0440aa9b1c5cb93ea09652",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Arial Negreta', 'Arial'",
                        "fontSize":"14px",
                        "fontWeight":"700",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":253,
                          "y":0},
                        "size":{
                          "width":97,
                          "height":30},
                        "cornerRadiusTopLeft":"120"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 写信给***",
                              "target":{
                                "targetType":"page",
                                "url":"写信给___.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/首页/u54.png"}},
{
                  "id":"484660832cec4ce9af646af9c922f22a",
                  "label":"",
                  "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":0,
                      "y":5},
                    "size":{
                      "width":108,
                      "height":25}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1a3f0019258b4d2b87bc2ec763a914ad",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":0,
                          "y":5},
                        "size":{
                          "width":108,
                          "height":25}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"切换 断绝联系 淡入淡出 500 ms",
                              "objectsToFades":[{
                                  "objectPath":["04512c70897f48269b2188dce72e1919"],
                                  "fadeInfo":{
                                    "fadeType":"toggle",
                                    "options":{
                                      "easing":"fade",
                                      "duration":500,
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d4c6c65286004ebdb60154a89e9084c6",
                  "label":"",
                  "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":374,
                      "y":9},
                    "size":{
                      "width":14,
                      "height":14}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bdded5f4d1e540bc99133d9ebe50918a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"1ab90ed1c46d42f1bb6f9ab88c5a2133",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":374,
                          "y":9},
                        "size":{
                          "width":14,
                          "height":14}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/首页/u58.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "a53c1a44c028446a89d109b2813655b2":{
      "scriptId":"u0"},
    "5ec225b47b8b4b0399bed8483ce2200d":{
      "scriptId":"u1"},
    "28dfe58f539e4772a9798add4deb6571":{
      "scriptId":"u2"},
    "7911f8e305844af8b7b27d61f9878f02":{
      "scriptId":"u3"},
    "df4f233d8dbe4a5cb175b9b4dcb4d071":{
      "scriptId":"u4"},
    "4c34cf160c5b4bd5a3e1e274176e6299":{
      "scriptId":"u5"},
    "30bc9dfed0d949c4a27c485736656d74":{
      "scriptId":"u6"},
    "1b2db4d93b7b45ed8247629838ba6b18":{
      "scriptId":"u7"},
    "324a0911aec94fb5adf3c40da80b81ce":{
      "scriptId":"u8"},
    "ee2ff7a7e42b4ea397b2cd1f41a24e26":{
      "scriptId":"u9"},
    "b6d4d119a8b44aaf89ccfb9d11e1f7e2":{
      "scriptId":"u10"},
    "1bbeeb689d3c458e842f43d7d564fa5c":{
      "scriptId":"u11"},
    "677935c987c34a53b1c7136fbb3c850e":{
      "scriptId":"u12"},
    "1e783469f3bc47828eb4e5ab61542d48":{
      "scriptId":"u13"},
    "32ae59a76dc14b338a88d4a849a43061":{
      "scriptId":"u14"},
    "1e693885f12b45b78cb8aa4b50f6ea5b":{
      "scriptId":"u15"},
    "405b8a0c3d234113a3e79492db6e6227":{
      "scriptId":"u16"},
    "89f5de0fbef3434598fe5777816054c5":{
      "scriptId":"u17"},
    "d838093848c64d639b2fbff72f0392a2":{
      "scriptId":"u18"},
    "36650022d6e14551b905b1b2193b980a":{
      "scriptId":"u19"},
    "e7dbe5d2c9ec4ca1afbab5dbc9d7fd64":{
      "scriptId":"u20"},
    "23940dfd01a0442ab868df12b06bc4ae":{
      "scriptId":"u21"},
    "fb104fe50fc7450c8a9e848a206c2d77":{
      "scriptId":"u22"},
    "7a4546283ff640d5a6714144a0dac5d3":{
      "scriptId":"u23"},
    "b3dfb053ef004096a3e5ded50c98fd4c":{
      "scriptId":"u24"},
    "508f218b3d154aa6b14c0f0e352a4f54":{
      "scriptId":"u25"},
    "ea3f9a6335e54e569162dee0ce1acd62":{
      "scriptId":"u26"},
    "33646037a1ed487f8294de284c0192a6":{
      "scriptId":"u27"},
    "d0d1be02ac5544bfa74aaf6f1737c14a":{
      "scriptId":"u28"},
    "4ae580a652624e88b26f60d2093b0d18":{
      "scriptId":"u29"},
    "17108429f5ca4f5e88737d47a23dae7c":{
      "scriptId":"u30"},
    "e8236a522ae34b33837b4f4e5b8ad146":{
      "scriptId":"u31"},
    "a4ed043d45bf4fc29f53735ce9ccb9ca":{
      "scriptId":"u32"},
    "14fdec0cff2b4a76a108626f9639acd1":{
      "scriptId":"u33"},
    "ea24446e978a47249f0af1d074777127":{
      "scriptId":"u34"},
    "9b1e18fa6b434744a86914fa15193d5f":{
      "scriptId":"u35"},
    "8d88bbf4f4434313b4f4e2a5a6027878":{
      "scriptId":"u36"},
    "e40714a20e0f4d7a9a4dae9682d41056":{
      "scriptId":"u37"},
    "5677098bc52b4556b8cc7f25e2d878c0":{
      "scriptId":"u38"},
    "343229686f964a6aae72811ede0941ad":{
      "scriptId":"u39"},
    "d9203771d21a471a84da368af38270c8":{
      "scriptId":"u40"},
    "69540251a5394effae46b02cabddf5c2":{
      "scriptId":"u41"},
    "5d77921a14a04168a276f7547589b9a4":{
      "scriptId":"u42"},
    "691b4f43d0c14d77a25331268eb6744e":{
      "scriptId":"u43"},
    "8ef2c778805e460abb178503143c938e":{
      "scriptId":"u44"},
    "65bd99223c4442adb68f158bb3cc9dc9":{
      "scriptId":"u45"},
    "05c0363e8d744f3285d9ebce2ffb309e":{
      "scriptId":"u46"},
    "3bc818505bbd42dab57308f6d15e6520":{
      "scriptId":"u47"},
    "04512c70897f48269b2188dce72e1919":{
      "scriptId":"u48"},
    "f3734067f28e4a7ab0b32638631d876a":{
      "scriptId":"u49"},
    "7a5fc61e300f429b85629fe87f6a6370":{
      "scriptId":"u50"},
    "1ab90ed1c46d42f1bb6f9ab88c5a2133":{
      "scriptId":"u51"},
    "192d33b0de3443d4810173846d2c4183":{
      "scriptId":"u52"},
    "333a83aadb054053afad7b3355b78b2a":{
      "scriptId":"u53"},
    "e8090581f8ce46679ffada4f3cc719ed":{
      "scriptId":"u54"},
    "ce0e430f1b0440aa9b1c5cb93ea09652":{
      "scriptId":"u55"},
    "484660832cec4ce9af646af9c922f22a":{
      "scriptId":"u56"},
    "1a3f0019258b4d2b87bc2ec763a914ad":{
      "scriptId":"u57"},
    "d4c6c65286004ebdb60154a89e9084c6":{
      "scriptId":"u58"},
    "bdded5f4d1e540bc99133d9ebe50918a":{
      "scriptId":"u59"}}});