$axure.loadCurrentPage({
  "url":"写信给___.html",
  "generationDate":new Date(1463658740682.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a2d49d007c874b8fae7d334ea2d0c003",
    "type":"Axure:Page",
    "name":"写信给***",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f59b2f421d17467dbf56f04d79e290a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":798,
              "height":41},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"990ccf86cef64d7894739e895661b3d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":798,
                  "height":41},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u0.png"}},
{
          "id":"3ad95786d11047828c26af37cb56dad1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":51},
            "size":{
              "width":798,
              "height":489},
            "cornerRadiusTopLeft":"8"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bb8dffae64f41398b0a873f20d6b6ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":51},
                "size":{
                  "width":798,
                  "height":489},
                "cornerRadiusTopLeft":"8"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u36.png"}},
{
          "id":"1d7253565435464cbb1bb6ab9911bfe0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":644,
              "y":462},
            "size":{
              "width":96,
              "height":42},
            "cornerRadiusTopLeft":"30"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78f548709d8b484ea898111d0d537d12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":644,
                  "y":462},
                "size":{
                  "width":96,
                  "height":42},
                "cornerRadiusTopLeft":"30"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u5.png"}},
{
          "id":"d7a52fad14294e78bc3657979ce2bc54",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Bold', '方正舒体'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":29,
              "y":6},
            "size":{
              "width":59,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d871b90f6dd4a74b031c82546559c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Bold', '方正舒体'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":29,
                  "y":6},
                "size":{
                  "width":59,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01ddf20ed878430c9f473ab3268fcc7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":5},
            "size":{
              "width":30,
              "height":30},
            "cornerRadiusTopLeft":"120"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"655a81c0f5564a47afdb63266e394a1c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":5},
                "size":{
                  "width":30,
                  "height":30},
                "cornerRadiusTopLeft":"120"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u44.png"}},
{
          "id":"831b25de477442edb5462c711b78577e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":755.5,
              "y":11},
            "size":{
              "width":19,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6b8f84a5ba4451a8392f97e5e40f3e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":755.5,
                  "y":11},
                "size":{
                  "width":19,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页/u46.png"}},
{
          "id":"a2e143d479ce4747b6569dec08547712",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":345,
              "y":10},
            "size":{
              "width":108,
              "height":25}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6fb7e4026f25408e85aab58a6fd35536",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微軟正黑體 Regular', '微軟正黑體'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":345,
                  "y":10},
                "size":{
                  "width":108,
                  "height":25}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f59b2f421d17467dbf56f04d79e290a1":{
      "scriptId":"u0"},
    "990ccf86cef64d7894739e895661b3d6":{
      "scriptId":"u1"},
    "3ad95786d11047828c26af37cb56dad1":{
      "scriptId":"u2"},
    "2bb8dffae64f41398b0a873f20d6b6ef":{
      "scriptId":"u3"},
    "1d7253565435464cbb1bb6ab9911bfe0":{
      "scriptId":"u4"},
    "78f548709d8b484ea898111d0d537d12":{
      "scriptId":"u5"},
    "d7a52fad14294e78bc3657979ce2bc54":{
      "scriptId":"u6"},
    "1d871b90f6dd4a74b031c82546559c37":{
      "scriptId":"u7"},
    "01ddf20ed878430c9f473ab3268fcc7f":{
      "scriptId":"u8"},
    "655a81c0f5564a47afdb63266e394a1c":{
      "scriptId":"u9"},
    "831b25de477442edb5462c711b78577e":{
      "scriptId":"u10"},
    "d6b8f84a5ba4451a8392f97e5e40f3e3":{
      "scriptId":"u11"},
    "a2e143d479ce4747b6569dec08547712":{
      "scriptId":"u12"},
    "6fb7e4026f25408e85aab58a6fd35536":{
      "scriptId":"u13"}}});