$axure.loadCurrentPage({
  "url":"登录_注册.html",
  "generationDate":new Date(1463658740375.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e24ac28839f44a24ba689fc17988b2ff",
    "type":"Axure:Page",
    "name":"登录/注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"066c5ca67f3f44db8fde93ddaa6ad0d2",
          "label":"登录注册",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"0ff069bb734d4ce5a028badd859a4d57",
              "label":"登录注册",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1527b60ad2ae483e940c1cb547d28184",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":797,
                      "height":559}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b2b40224b984721941f575f3de12be1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":797,
                          "height":559}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u1.png"}},
{
                  "id":"27d3b37bacac4eba834098d8f6e3be04",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"h1",
                  "visible":true,
                  "style":{
                    "fontName":"'方正舒体 Regular', '方正舒体'",
                    "fontSize":"72px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":325,
                      "y":89},
                    "size":{
                      "width":147,
                      "height":76}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b48d866a10304e30b56a1567a29d667b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'方正舒体 Regular', '方正舒体'",
                        "fontSize":"72px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":325,
                          "y":89},
                        "size":{
                          "width":147,
                          "height":76}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b25ae81b257f4e45a43c28ef6f23c0e8",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "location":{
                      "x":245.5,
                      "y":305},
                    "size":{
                      "width":128,
                      "height":51},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"02d1dbf8f1b84d5e92c6b5d16163f718",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"18px",
                        "location":{
                          "x":245.5,
                          "y":305},
                        "size":{
                          "width":128,
                          "height":51},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 登录注册 to 登录 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["066c5ca67f3f44db8fde93ddaa6ad0d2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录_注册/u5.png"}},
{
                  "id":"5530cbe5f05b4751b80da4a26768f2c8",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "location":{
                      "x":423.5,
                      "y":305},
                    "size":{
                      "width":128,
                      "height":51},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1fc419c5bcb54ea2baf45d10a6eebed1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"18px",
                        "location":{
                          "x":423.5,
                          "y":305},
                        "size":{
                          "width":128,
                          "height":51},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 登录注册 to 注册 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["066c5ca67f3f44db8fde93ddaa6ad0d2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录_注册/u5.png"}},
{
                  "id":"a05e3b84eb534dab8f533a84cc159ed4",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":314,
                      "y":219},
                    "size":{
                      "width":170,
                      "height":19}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"db31219b82594c34b68670fe223fc806",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":314,
                          "y":219},
                        "size":{
                          "width":170,
                          "height":19}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"811dfc08e0904a88b88663778b07905b",
              "label":"登录",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"74c40460cf8c48778314210c9b0a149c",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":797,
                      "height":559}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b2a012b805094aa5a9facef4edc4bd03",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":797,
                          "height":559}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u1.png"}},
{
                  "id":"f43882ee67a147f1a0ac52d30004fd52",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "location":{
                      "x":246,
                      "y":305},
                    "size":{
                      "width":306,
                      "height":51},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cc1dac2611ac40768f2022e64a32a7ec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"18px",
                        "location":{
                          "x":246,
                          "y":305},
                        "size":{
                          "width":306,
                          "height":51},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 首页",
                              "target":{
                                "targetType":"page",
                                "url":"首页.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录_注册/u13.png"}},
{
                  "id":"7553646eac6348c4b8e454431689996f",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":117},
                    "size":{
                      "width":306,
                      "height":159},
                    "cornerRadiusTopLeft":"20"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0e46c9478eb74f00942cff6411bc6207",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":246,
                          "y":117},
                        "size":{
                          "width":306,
                          "height":159},
                        "cornerRadiusTopLeft":"20"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u15.png"}},
{
                  "id":"7e068c5b110d40dc94e75cf247abed21",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":321,
                      "y":141},
                    "size":{
                      "width":213,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e126a5dcc5494609804e75fdcb25c8a6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":321,
                          "y":141},
                        "size":{
                          "width":213,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u17.png"}},
{
                  "id":"01f4bc0c2ccc489fa04bd52c778e5432",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":152},
                    "size":{
                      "width":53,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b31f03495a24434b9e60e05b1fe6e88b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":152},
                        "size":{
                          "width":53,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b0be0a3a55174220bef831510aaed617",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":321,
                      "y":189},
                    "size":{
                      "width":213,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b6e19347b8784e47a9746170ae92a71e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":321,
                          "y":189},
                        "size":{
                          "width":213,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u17.png"}},
{
                  "id":"d941966de0114c0b911031ca944abe25",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":200},
                    "size":{
                      "width":40,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b62b65c5d33d46268f1db538281cba50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":200},
                        "size":{
                          "width":40,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"10f780d8569043c5929f81bde53d9515",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":473,
                      "y":247},
                    "size":{
                      "width":61,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e914f14899464e359d70006617ef2f86",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":473,
                          "y":247},
                        "size":{
                          "width":61,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6326e3f531e74aa9a7821adae3a6513c",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"checkbox",
                  "styleType":"checkbox",
                  "visible":true,
                  "style":{
                    "fontSize":"12px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF999999,
                      "opacity":1},
                    "location":{
                      "x":278,
                      "y":246},
                    "size":{
                      "width":100,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"17c44a0a4e284893ab163fe3c0977957",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"12px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1},
                        "location":{
                          "x":278,
                          "y":246},
                        "size":{
                          "width":100,
                          "height":15}},
                      "adaptiveStyles":{
}}]}]},
{
              "id":"c89fb5b34aeb46ffb12d8fcadc89815f",
              "label":"注册",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"befb41374bb741d39bd2c4bb075a2e59",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":797,
                      "height":559}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"097c4d06f469414a93aa118bea2f0fbe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":797,
                          "height":559}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u1.png"}},
{
                  "id":"8977d7bf7b054a13953bda9eb6a72c71",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"18px",
                    "location":{
                      "x":246,
                      "y":379},
                    "size":{
                      "width":306,
                      "height":51},
                    "cornerRadiusTopLeft":"28"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ee6a0105fba34d9883ae68e66571a56f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"18px",
                        "location":{
                          "x":246,
                          "y":379},
                        "size":{
                          "width":306,
                          "height":51},
                        "cornerRadiusTopLeft":"28"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 登录注册 to 登录 淡入淡出 in 500ms",
                              "panelsToStates":[{
                                  "panelPath":["066c5ca67f3f44db8fde93ddaa6ad0d2"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "animateIn":{
                                        "easing":"fade",
                                        "duration":500},
                                      "compress":false}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/登录_注册/u13.png"}},
{
                  "id":"169414672a5a457e87bb926e249f4d19",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":246,
                      "y":117},
                    "size":{
                      "width":306,
                      "height":226},
                    "cornerRadiusTopLeft":"20"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3ad34e54dc0c4c928648a9d6e809b081",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":246,
                          "y":117},
                        "size":{
                          "width":306,
                          "height":226},
                        "cornerRadiusTopLeft":"20"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u33.png"}},
{
                  "id":"1dae20b46a3f4b96819c9cdcfa9bc939",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":347,
                      "y":141},
                    "size":{
                      "width":187,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2d35cdf68e62434a98cac5ef1c4c044d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":347,
                          "y":141},
                        "size":{
                          "width":187,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u35.png"}},
{
                  "id":"3bd5ef80488746a1bf58800993258602",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":152},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dbc03777b10b40eeb220e063b3191c78",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":152},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d7868b2d1d4f49ccb13367ef01894101",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":347,
                      "y":189},
                    "size":{
                      "width":187,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7f09985e429e4c9283bff9ddf29369a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":347,
                          "y":189},
                        "size":{
                          "width":187,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u35.png"}},
{
                  "id":"48102ad803704899a11e5dbd178700d0",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":200},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ecd0764dd1f5425bb9e546197a4140d4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":200},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0740f6b27a344b0f90e7e592854fe5e1",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":347,
                      "y":238},
                    "size":{
                      "width":187,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a99dcd2565144cce96cb548059657b4f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":347,
                          "y":238},
                        "size":{
                          "width":187,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u35.png"}},
{
                  "id":"e6db73db983d404c811511169ef73cbb",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF666666,
                      "opacity":1},
                    "location":{
                      "x":258,
                      "y":249},
                    "size":{
                      "width":66,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"308bf169685849f38af773ea7303ce1b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF666666,
                          "opacity":1},
                        "location":{
                          "x":258,
                          "y":249},
                        "size":{
                          "width":66,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1e73353b4403469eb5f0a0919346ca7e",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":258,
                      "y":299},
                    "size":{
                      "width":79,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4a94c575b774d9e86d02ff17b0af19e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":258,
                          "y":299},
                        "size":{
                          "width":79,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7abf92a1fecf447db08bcdbe3f071a0f",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":347,
                      "y":286},
                    "size":{
                      "width":95,
                      "height":38},
                    "cornerRadiusTopLeft":"12"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"72ffca3965c546bc9063dec5813fd7ae",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":347,
                          "y":286},
                        "size":{
                          "width":95,
                          "height":38},
                        "cornerRadiusTopLeft":"12"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u49.png"}},
{
                  "id":"57e239026bcd4ad999e5925b8a57c5de",
                  "label":"",
                  "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":467,
                      "y":286},
                    "size":{
                      "width":67,
                      "height":38}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"848ae6a4afed4dbb8c60c19e5e829a73",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"066c5ca67f3f44db8fde93ddaa6ad0d2",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":467,
                          "y":286},
                        "size":{
                          "width":67,
                          "height":38}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/登录_注册/u51.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "066c5ca67f3f44db8fde93ddaa6ad0d2":{
      "scriptId":"u0"},
    "1527b60ad2ae483e940c1cb547d28184":{
      "scriptId":"u1"},
    "7b2b40224b984721941f575f3de12be1":{
      "scriptId":"u2"},
    "27d3b37bacac4eba834098d8f6e3be04":{
      "scriptId":"u3"},
    "b48d866a10304e30b56a1567a29d667b":{
      "scriptId":"u4"},
    "b25ae81b257f4e45a43c28ef6f23c0e8":{
      "scriptId":"u5"},
    "02d1dbf8f1b84d5e92c6b5d16163f718":{
      "scriptId":"u6"},
    "5530cbe5f05b4751b80da4a26768f2c8":{
      "scriptId":"u7"},
    "1fc419c5bcb54ea2baf45d10a6eebed1":{
      "scriptId":"u8"},
    "a05e3b84eb534dab8f533a84cc159ed4":{
      "scriptId":"u9"},
    "db31219b82594c34b68670fe223fc806":{
      "scriptId":"u10"},
    "74c40460cf8c48778314210c9b0a149c":{
      "scriptId":"u11"},
    "b2a012b805094aa5a9facef4edc4bd03":{
      "scriptId":"u12"},
    "f43882ee67a147f1a0ac52d30004fd52":{
      "scriptId":"u13"},
    "cc1dac2611ac40768f2022e64a32a7ec":{
      "scriptId":"u14"},
    "7553646eac6348c4b8e454431689996f":{
      "scriptId":"u15"},
    "0e46c9478eb74f00942cff6411bc6207":{
      "scriptId":"u16"},
    "7e068c5b110d40dc94e75cf247abed21":{
      "scriptId":"u17"},
    "e126a5dcc5494609804e75fdcb25c8a6":{
      "scriptId":"u18"},
    "01f4bc0c2ccc489fa04bd52c778e5432":{
      "scriptId":"u19"},
    "b31f03495a24434b9e60e05b1fe6e88b":{
      "scriptId":"u20"},
    "b0be0a3a55174220bef831510aaed617":{
      "scriptId":"u21"},
    "b6e19347b8784e47a9746170ae92a71e":{
      "scriptId":"u22"},
    "d941966de0114c0b911031ca944abe25":{
      "scriptId":"u23"},
    "b62b65c5d33d46268f1db538281cba50":{
      "scriptId":"u24"},
    "10f780d8569043c5929f81bde53d9515":{
      "scriptId":"u25"},
    "e914f14899464e359d70006617ef2f86":{
      "scriptId":"u26"},
    "6326e3f531e74aa9a7821adae3a6513c":{
      "scriptId":"u27"},
    "17c44a0a4e284893ab163fe3c0977957":{
      "scriptId":"u28"},
    "befb41374bb741d39bd2c4bb075a2e59":{
      "scriptId":"u29"},
    "097c4d06f469414a93aa118bea2f0fbe":{
      "scriptId":"u30"},
    "8977d7bf7b054a13953bda9eb6a72c71":{
      "scriptId":"u31"},
    "ee6a0105fba34d9883ae68e66571a56f":{
      "scriptId":"u32"},
    "169414672a5a457e87bb926e249f4d19":{
      "scriptId":"u33"},
    "3ad34e54dc0c4c928648a9d6e809b081":{
      "scriptId":"u34"},
    "1dae20b46a3f4b96819c9cdcfa9bc939":{
      "scriptId":"u35"},
    "2d35cdf68e62434a98cac5ef1c4c044d":{
      "scriptId":"u36"},
    "3bd5ef80488746a1bf58800993258602":{
      "scriptId":"u37"},
    "dbc03777b10b40eeb220e063b3191c78":{
      "scriptId":"u38"},
    "d7868b2d1d4f49ccb13367ef01894101":{
      "scriptId":"u39"},
    "7f09985e429e4c9283bff9ddf29369a4":{
      "scriptId":"u40"},
    "48102ad803704899a11e5dbd178700d0":{
      "scriptId":"u41"},
    "ecd0764dd1f5425bb9e546197a4140d4":{
      "scriptId":"u42"},
    "0740f6b27a344b0f90e7e592854fe5e1":{
      "scriptId":"u43"},
    "a99dcd2565144cce96cb548059657b4f":{
      "scriptId":"u44"},
    "e6db73db983d404c811511169ef73cbb":{
      "scriptId":"u45"},
    "308bf169685849f38af773ea7303ce1b":{
      "scriptId":"u46"},
    "1e73353b4403469eb5f0a0919346ca7e":{
      "scriptId":"u47"},
    "e4a94c575b774d9e86d02ff17b0af19e":{
      "scriptId":"u48"},
    "7abf92a1fecf447db08bcdbe3f071a0f":{
      "scriptId":"u49"},
    "72ffca3965c546bc9063dec5813fd7ae":{
      "scriptId":"u50"},
    "57e239026bcd4ad999e5925b8a57c5de":{
      "scriptId":"u51"},
    "848ae6a4afed4dbb8c60c19e5e829a73":{
      "scriptId":"u52"}}});